name: crm_backend

services:

  mysql:
    image: mysql:8
    restart: unless-stopped
    container_name: crm-mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - crm-mysql-network
    healthcheck:
      test: mysqladmin ping -h localhost -u ${DB_USERNAME} -p${DB_PASSWORD}
      interval: 5s
      timeout: 10s
      retries: 20

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: crm-phpmyadmin
    restart: unless-stopped
    ports:
      - '8086:80'
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
      PMA_ABSOLUTE_URI: ${APP_URL}/phpmyadmin/
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - crm-mysql-network
      - crm-webserver-network

  redis:
    image: redis:7.2.4-alpine
    container_name: crm-redis
    restart: unless-stopped
    command:
      - 'redis-server'
      - '--requirepass ${REDIS_PASSWORD}'
    volumes:
      - ./docker/redis:/data
    networks:
      - crm-redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 10s
      retries: 20

  app: &app
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    container_name: crm-app
    restart: unless-stopped
    user: ${UID}:${GID}
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./:/var/www
      - crm_app_composer_data:/.composer
      - crm_app_npm_data:/.npm
    working_dir: /var/www
    environment:
      COMMAND: php artisan serve --host=0.0.0.0 --port=8001
      PROCESS: app
    ports:
      - "8001:8001"
    networks:
      - crm-mysql-network
      - crm-webserver-network
      - crm-redis-network

  horizon:
    <<: *app
    container_name: crm-horizon
    environment:
      COMMAND: php artisan horizon
      PROCESS: horizon
    ports: []  # remove hosting of external ports
    networks:
      - crm-mysql-network
      - crm-redis-network

  schedule:
    <<: *app
    container_name: crm-schedule
    environment:
      COMMAND: supercronic -quiet /var/www/docker/php/schedule/crontab
      PROCESS: schedule
    ports: []  # remove hosting of external ports
    networks:
      - crm-mysql-network
      - crm-redis-network

  webserver:
    image: nginx:1.26.0-alpine
    container_name: crm-webserver
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./storage/logs/nginx/:/var/log/nginx/
    ports:
      - "8000:80"
    networks:
      - crm-webserver-network
      - crm-mysql-network
    depends_on:
      app:
        condition: service_started
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
  redis_data:
  crm_app_composer_data:
  crm_app_npm_data:
  # crm_rabbitmq_data:

networks:
  crm-mysql-network:
  crm-webserver-network:
  crm-redis-network:
  # crm-rabbitmq-network:
